import Head from 'next/head'
import Script from 'next/script'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';
import fs from "fs";

export const getStaticProps = async () => {
  const files = fs.readdirSync("posts");
  return {
    props: {
      slugs: files.map(filename => filename.replace(".md", ""))
    }
  };
};


export default function Home({slugs}) {

  if(!slugs || slugs.length === 0) {
    return <>
      <Head>
        <title>Blog Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon/favicon.ico" />
        <Script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></Script>
      </Head>
      <main className={`text-center mt-5 mb-5`}>
        <h3>No Articles Found!</h3>
      </main>
    </>
  }

  return (
    <>
      <Head>
        <title>Blog Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon/favicon.ico" />
        <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
      </Head>
      <main className={`container blog-page`}>
        {slugs && slugs.map((post) => {
          return <Link href={"/blog-posts/"+post} key={post}>
            <div className={`${styles["blog-post"]} shadow-sm`}>
              <h4>{post}</h4>
              <p className={styles.time}>Sometime</p>
              <p className={styles.description}>Some description</p>
            </div>
          </Link>
        })}
      </main>
    </>
  )
}
